# Generated by Django 2.2.7 on 2019-11-08 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='modified_on',
            field=models.DateTimeField(null=True),
        ),
    ]
