# Generated by Django 2.2.7 on 2019-11-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0009_approvalstatus_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='documentno',
            field=models.IntegerField(default=1000),
        ),
    ]
