# Generated by Django 2.2.7 on 2019-11-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0011_lineofapprovaldetail_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
