# Generated by Django 2.2.7 on 2019-11-12 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinemaxpr', '0012_delete_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentno', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(null=True)),
                ('deadline_on', models.DateTimeField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('approvalstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.ApprovalStatus')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.BudgetDetail')),
                ('businessunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.businessunit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('must_approve', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('businessunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.businessunit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('extendeduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.ExtendedUser')),
                ('memo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.MemoDetail')),
                ('transactionstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.ApprovalStatus')),
            ],
        ),
    ]
