# Generated by Django 2.2.7 on 2019-11-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0014_transactiondetail_lineofapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='lineOfApproval',
            field=models.IntegerField(default=0),
        ),
    ]
