# Generated by Django 2.2.7 on 2019-11-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0015_auto_20191113_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='memo',
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='businessunit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='transactionstatus',
            field=models.IntegerField(default=1),
        ),
    ]
