# Generated by Django 2.2.7 on 2019-11-12 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0018_remove_transactiondetail_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='extendeduser',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.ExtendedUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='memo',
            field=models.IntegerField(default=1),
        ),
    ]
