# Generated by Django 2.2.7 on 2019-11-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0022_auto_20191114_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondetail',
            old_name='lineOfApproval',
            new_name='lineOfApprovalObj',
        ),
    ]
