# Generated by Django 2.2.7 on 2019-11-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0023_auto_20191114_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='transactionstatus',
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='extendeduserObj',
            field=models.IntegerField(default=1),
        ),
    ]
