# Generated by Django 2.2.7 on 2019-11-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0024_auto_20191114_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='transactionstatus',
            field=models.IntegerField(default=1),
        ),
    ]
