# Generated by Django 2.2.7 on 2019-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0025_transactiondetail_transactionstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineofapprovaldetail',
            name='must_approve',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='must_approve',
        ),
        migrations.AddField(
            model_name='lineofapprovaldetail',
            name='required_approval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='required_approval',
            field=models.IntegerField(default=1),
        ),
    ]
