# Generated by Django 2.2.7 on 2019-11-15 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinemaxpr', '0026_auto_20191115_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisitionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('deadline_on', models.DateTimeField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('budgetDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.BudgetDetail')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
