# Generated by Django 2.2.7 on 2019-11-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0027_purchaserequisitiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisitiondetail',
            name='transactionstatus',
            field=models.IntegerField(default=1),
        ),
    ]
