# Generated by Django 2.2.7 on 2019-11-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0028_purchaserequisitiondetail_transactionstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequisitiondetail',
            old_name='transactionstatus',
            new_name='status',
        ),
    ]
