# Generated by Django 2.2.7 on 2019-11-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0029_auto_20191116_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisitiondetail',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.ApprovalStatus'),
        ),
    ]
