# Generated by Django 2.2.7 on 2019-11-17 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0031_entitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstatus',
            name='entity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType'),
        ),
        migrations.AddField(
            model_name='budgetdetail',
            name='entity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='entity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='entity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType'),
        ),
        migrations.AddField(
            model_name='lineofapproval',
            name='entity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType'),
        ),
        migrations.AddField(
            model_name='lineofapprovaldetail',
            name='entity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType'),
        ),
        migrations.AddField(
            model_name='memodetail',
            name='entity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType'),
        ),
        migrations.AddField(
            model_name='purchaserequisitiondetail',
            name='entity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType'),
        ),
        migrations.AddField(
            model_name='role',
            name='entity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='entity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType'),
        ),
    ]
