# Generated by Django 2.2.7 on 2019-11-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinemaxpr', '0035_businessunit_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisitiondetail',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaserequisitiondetail',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaserequisitiondetail',
            name='require_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisitiondetail',
            name='vendor_account',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisitiondetail',
            name='vendor_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisitiondetail',
            name='budgetDetail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.BudgetDetail'),
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionLineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('line_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remark', models.CharField(max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('deadline_on', models.DateTimeField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType')),
                ('purchaseRequisitionDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.PurchaseRequisitionDetail')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.ApprovalStatus')),
            ],
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='purchaseRequisitionLineDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.PurchaseRequisitionLineDetail'),
        ),
    ]
