# Generated by Django 2.2.7 on 2019-11-18 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0036_auto_20191119_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisitiondetail',
            name='budgetDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.BudgetDetail'),
        ),
    ]
