# Generated by Django 2.2.7 on 2019-11-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0037_auto_20191119_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('attachment', models.FileField(upload_to='attachments')),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('content_type', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('entity_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType')),
                ('memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.MemoDetail')),
            ],
        ),
    ]
