# Generated by Django 2.2.7 on 2019-11-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0038_attachmentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentdetail',
            name='image',
        ),
    ]
