# Generated by Django 2.2.7 on 2019-11-20 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinemaxpr', '0039_remove_attachmentdetail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType')),
                ('purchaseRequisitionDetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.PurchaseRequisitionDetail')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('entity_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.EntityType')),
                ('purchaseOrderDetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.PurchaseOrderDetail')),
                ('purchaseRequisitionLineDetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.PurchaseRequisitionLineDetail')),
            ],
        ),
    ]
