# Generated by Django 2.2.7 on 2019-11-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaxpr', '0040_purchaseorderdetail_purchaseorderlinedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.ApprovalStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='purchaseOrderDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemaxpr.PurchaseOrderDetail'),
        ),
    ]
